
document.addEventListener('DOMContentLoaded', () => {
  const popup = document.getElementById('miningReminder');
  const closeBtn = popup.querySelector('.popup-close');

  const miningActiveRaw = localStorage.getItem('miningActive');
  const miningActive = miningActiveRaw === true || miningActiveRaw === 'true' || miningActiveRaw === '1';

  // ✅ Page-specific key
  const pageKey = 'miningPopupLastShown_' + window.location.pathname;
  const lastShown = parseInt(localStorage.getItem(pageKey) || '0', 10);

  const now = Date.now();
  const threeDays = 3 * 24 * 60 * 60 * 1000; // 3 din

  if (!miningActive && (now - lastShown > threeDays)) {
   const messages = [
  { heading: "<i class='fas fa-tasks icon1'></i> Complete Your Daily Umarae Task", text: "Hey <strong class='highlight'>Umarae user</strong>! Your daily task is ready. Complete it today to earn <strong class='highlight2'>exclusive rewards</strong> and stay on top of your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-clipboard-check icon2'></i> Daily Task Alert", text: "Hello <strong class='highlight'>Umarae member</strong>! Complete your task now to unlock <strong class='highlight2'>special bonuses</strong> and boost your <strong class='highlight'>earnings streak</strong>!" },
  { heading: "<i class='fas fa-star icon3'></i> Shine with Your Daily Task", text: "Keep shining, <strong class='highlight'>Umarae user</strong>! Complete today's task to claim <strong class='highlight2'>premium rewards</strong> and maintain your <strong class='highlight'>active streak</strong>!" },
  { heading: "<i class='fas fa-gem icon4'></i> Claim Your Rewards", text: "Your daily task is ready, <strong class='highlight'>Umarae user</strong>! Finish it to earn <strong class='highlight2'>extra tokens</strong> and maximize your <strong class='highlight'>platform benefits</strong>!" },
  { heading: "<i class='fas fa-rocket icon5'></i> Boost Your Earnings Today", text: "Hey <strong class='highlight'>Umarae member</strong>! Complete your daily task to activate <strong class='highlight2'>reward multipliers</strong> and grow your <strong class='highlight'>daily earnings</strong> faster!" },
  { heading: "<i class='fas fa-bolt icon6'></i> Lightning Task Alert", text: "Stay fast, <strong class='highlight'>Umarae user</strong>! Complete today's task to earn <strong class='highlight2'>exclusive bonuses</strong> and keep your <strong class='highlight'>earning streak</strong> alive!" },
  { heading: "<i class='fas fa-fire icon7'></i> Hot Daily Task", text: "Don't miss out, <strong class='highlight'>Umarae member</strong>! Complete your task now for <strong class='highlight2'>premium rewards</strong> and keep your <strong class='highlight'>daily streak</strong> going!" },
  { heading: "<i class='fas fa-trophy icon8'></i> Win with Daily Tasks", text: "Hello <strong class='highlight'>Umarae user</strong>! Completing your daily task unlocks <strong class='highlight2'>special bonuses</strong> and strengthens your <strong class='highlight'>platform progress</strong>!" },
  { heading: "<i class='fas fa-sun icon9'></i> Brighten Your Day with Rewards", text: "Good day, <strong class='highlight'>Umarae member</strong>! Finish today's task to gain <strong class='highlight2'>exclusive tokens</strong> and stay at the top of your <strong class='highlight'>earning game</strong>!" },
  { heading: "<i class='fas fa-gift icon10'></i> Your Daily Gift Awaits", text: "Hey <strong class='highlight'>Umarae user</strong>! Complete your daily task to unlock <strong class='highlight2'>rewards</strong> and maximize your <strong class='highlight'>platform earnings</strong> today!" },

  { heading: "<i class='fas fa-certificate icon11'></i> Daily Challenge Open", text: "Complete today's task, <strong class='highlight'>Umarae user</strong>, to claim <strong class='highlight2'>exclusive prizes</strong> and maintain your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-moon icon12'></i> Nightly Task Alert", text: "Keep active tonight, <strong class='highlight'>Umarae member</strong>! Finish your task to get <strong class='highlight2'>bonus rewards</strong> and grow your <strong class='highlight'>daily income</strong>!" },
  { heading: "<i class='fas fa-coins icon13'></i> Daily Coin Boost", text: "Hey <strong class='highlight'>Umarae user</strong>, complete the task to earn <strong class='highlight2'>extra coins</strong> and maximize your <strong class='highlight'>platform profits</strong>!" },
  { heading: "<i class='fas fa-heart icon14'></i> Love Your Daily Rewards", text: "Hello <strong class='highlight'>Umarae member</strong>! Complete your daily task to unlock <strong class='highlight2'>special bonuses</strong> and increase your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-lightbulb icon15'></i> Bright Ideas Earn Rewards", text: "Complete today's task, <strong class='highlight'>Umarae user</strong>, and earn <strong class='highlight2'>premium rewards</strong> while keeping your <strong class='highlight'>daily streak</strong> intact!" },
  { heading: "<i class='fas fa-rocket icon16'></i> Skyrocket Your Earnings", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your task to unlock <strong class='highlight2'>exclusive bonuses</strong> and boost your <strong class='highlight'>daily income</strong>!" },
  { heading: "<i class='fas fa-star-half-alt icon17'></i> Halfway to Rewards", text: "Keep moving, <strong class='highlight'>Umarae user</strong>! Complete the task to claim <strong class='highlight2'>daily prizes</strong> and stay active on your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-gift-card icon18'></i> Gift Your Effort", text: "Hello <strong class='highlight'>Umarae member</strong>! Finish your daily task to unlock <strong class='highlight2'>bonus rewards</strong> and enhance your <strong class='highlight'>platform progress</strong>!" },
  { heading: "<i class='fas fa-clock icon19'></i> Time-Sensitive Task", text: "Don't wait, <strong class='highlight'>Umarae user</strong>! Complete your task now for <strong class='highlight2'>exclusive bonuses</strong> and maintain your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-chart-line icon20'></i> Boost Your Stats", text: "Hello <strong class='highlight'>Umarae member</strong>! Completing your task today earns <strong class='highlight2'>special rewards</strong> and keeps your <strong class='highlight'>daily streak</strong> alive!" },
  { heading: "<i class='fas fa-clipboard icon21'></i> Stay Ahead with Your Task", text: "Complete today’s task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>exclusive bonuses</strong> and grow your <strong class='highlight'>daily rewards</strong>!" },
  { heading: "<i class='fas fa-dice icon22'></i> Take a Chance, Earn Rewards", text: "Hey <strong class='highlight'>Umarae member</strong>! Complete your task for <strong class='highlight2'>special rewards</strong> and keep your <strong class='highlight'>earning streak</strong> alive!" },
  { heading: "<i class='fas fa-bell icon23'></i> Don’t Miss Today’s Task", text: "Hello <strong class='highlight'>Umarae user</strong>! Finish your daily task to gain <strong class='highlight2'>premium tokens</strong> and boost your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-key icon24'></i> Unlock Daily Bonuses", text: "Stay active, <strong class='highlight'>Umarae member</strong>! Complete today’s task to unlock <strong class='highlight2'>exclusive prizes</strong> and maximize your <strong class='highlight'>daily rewards</strong>!" },
  { heading: "<i class='fas fa-crown icon25'></i> Be the Daily Champion", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete your task to earn <strong class='highlight2'>premium rewards</strong> and maintain your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-paper-plane icon26'></i> Send Your Effort, Get Rewards", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task for <strong class='highlight2'>exclusive bonuses</strong> and grow your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-lightning icon27'></i> Lightning Task Alert", text: "Complete your daily task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>special rewards</strong> and boost your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-moon icon28'></i> Nightly Task Opportunity", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your task tonight for <strong class='highlight2'>premium bonuses</strong> and maximize your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-star icon29'></i> Star Performance Daily Task", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to earn <strong class='highlight2'>exclusive rewards</strong> and maintain your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-gift icon30'></i> Your Daily Gift Awaits", text: "Complete your task, <strong class='highlight'>Umarae member</strong>, to claim <strong class='highlight2'>premium tokens</strong> and keep your <strong class='highlight'>streak</strong> alive!" },
  { heading: "<i class='fas fa-heart icon31'></i> Reward Your Effort", text: "Hey <strong class='highlight'>Umarae user</strong>! Finish your daily task to unlock <strong class='highlight2'>special bonuses</strong> and grow your <strong class='highlight'>daily rewards</strong>!" },
  { heading: "<i class='fas fa-rocket icon32'></i> Launch Your Daily Rewards", text: "Hello <strong class='highlight'>Umarae member</strong>! Complete the task to earn <strong class='highlight2'>exclusive bonuses</strong> and maintain your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-gem icon33'></i> Daily Gem Awaits", text: "Complete today’s task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>premium rewards</strong> and maximize your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-trophy icon34'></i> Claim Your Trophy", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your daily task to earn <strong class='highlight2'>exclusive prizes</strong> and keep your <strong class='highlight'>streak</strong> alive!" },
  { heading: "<i class='fas fa-bolt icon35'></i> Strike with Your Task", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to unlock <strong class='highlight2'>special rewards</strong> and grow your <strong class='highlight'>daily streak</strong>!" },
  { heading: "<i class='fas fa-lightbulb icon36'></i> Bright Task Rewards", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your daily task to claim <strong class='highlight2'>premium bonuses</strong> and maximize your <strong class='highlight'>earnings</strong>!" },
  { heading: "<i class='fas fa-chart-line icon37'></i> Track Your Earnings", text: "Complete today’s task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>exclusive rewards</strong> and boost your <strong class='highlight'>daily income</strong>!" },
  { heading: "<i class='fas fa-star-half-alt icon38'></i> Halfway to Bonus", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your task to claim <strong class='highlight2'>special rewards</strong> and maintain your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-moon icon39'></i> Nightly Reward Awaits", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to earn <strong class='highlight2'>premium bonuses</strong> and boost your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-dice icon40'></i> Roll for Rewards", text: "Complete your daily task, <strong class='highlight'>Umarae member</strong>, to unlock <strong class='highlight2'>exclusive prizes</strong> and keep your <strong class='highlight'>streak</strong> alive!" },
  { heading: "<i class='fas fa-clipboard icon21'></i> Stay Ahead with Your Task", text: "Complete today’s task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>exclusive bonuses</strong> and grow your <strong class='highlight'>daily rewards</strong>!" },
  { heading: "<i class='fas fa-dice icon22'></i> Take a Chance, Earn Rewards", text: "Hey <strong class='highlight'>Umarae member</strong>! Complete your task for <strong class='highlight2'>special rewards</strong> and keep your <strong class='highlight'>earning streak</strong> alive!" },
  { heading: "<i class='fas fa-bell icon23'></i> Don’t Miss Today’s Task", text: "Hello <strong class='highlight'>Umarae user</strong>! Finish your daily task to gain <strong class='highlight2'>premium tokens</strong> and boost your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-key icon24'></i> Unlock Daily Bonuses", text: "Stay active, <strong class='highlight'>Umarae member</strong>! Complete today’s task to unlock <strong class='highlight2'>exclusive prizes</strong> and maximize your <strong class='highlight'>daily rewards</strong>!" },
  { heading: "<i class='fas fa-crown icon25'></i> Be the Daily Champion", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete your task to earn <strong class='highlight2'>premium rewards</strong> and maintain your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-paper-plane icon26'></i> Send Your Effort, Get Rewards", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task for <strong class='highlight2'>exclusive bonuses</strong> and grow your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-lightning icon27'></i> Lightning Task Alert", text: "Complete your daily task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>special rewards</strong> and boost your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-moon icon28'></i> Nightly Task Opportunity", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your task tonight for <strong class='highlight2'>premium bonuses</strong> and maximize your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-star icon29'></i> Star Performance Daily Task", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to earn <strong class='highlight2'>exclusive rewards</strong> and maintain your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-gift icon30'></i> Your Daily Gift Awaits", text: "Complete your task, <strong class='highlight'>Umarae member</strong>, to claim <strong class='highlight2'>premium tokens</strong> and keep your <strong class='highlight'>streak</strong> alive!" },
  { heading: "<i class='fas fa-heart icon31'></i> Reward Your Effort", text: "Hey <strong class='highlight'>Umarae user</strong>! Finish your daily task to unlock <strong class='highlight2'>special bonuses</strong> and grow your <strong class='highlight'>daily rewards</strong>!" },
  { heading: "<i class='fas fa-rocket icon32'></i> Launch Your Daily Rewards", text: "Hello <strong class='highlight'>Umarae member</strong>! Complete the task to earn <strong class='highlight2'>exclusive bonuses</strong> and maintain your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-gem icon33'></i> Daily Gem Awaits", text: "Complete today’s task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>premium rewards</strong> and maximize your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-trophy icon34'></i> Claim Your Trophy", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your daily task to earn <strong class='highlight2'>exclusive prizes</strong> and keep your <strong class='highlight'>streak</strong> alive!" },
  { heading: "<i class='fas fa-bolt icon35'></i> Strike with Your Task", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to unlock <strong class='highlight2'>special rewards</strong> and grow your <strong class='highlight'>daily streak</strong>!" },
  { heading: "<i class='fas fa-lightbulb icon36'></i> Bright Task Rewards", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your daily task to claim <strong class='highlight2'>premium bonuses</strong> and maximize your <strong class='highlight'>earnings</strong>!" },
  { heading: "<i class='fas fa-chart-line icon37'></i> Track Your Earnings", text: "Complete today’s task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>exclusive rewards</strong> and boost your <strong class='highlight'>daily income</strong>!" },
  { heading: "<i class='fas fa-star-half-alt icon38'></i> Halfway to Bonus", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your task to claim <strong class='highlight2'>special rewards</strong> and maintain your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-moon icon39'></i> Nightly Reward Awaits", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to earn <strong class='highlight2'>premium bonuses</strong> and boost your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-dice icon40'></i> Roll for Rewards", text: "Complete your daily task, <strong class='highlight'>Umarae member</strong>, to unlock <strong class='highlight2'>exclusive prizes</strong> and keep your <strong class='highlight'>streak</strong> alive!" },
  { heading: "<i class='fas fa-gift icon61'></i> Daily Gift Awaits", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete your task today to earn <strong class='highlight2'>special rewards</strong> and keep your <strong class='highlight'>streak alive</strong>!" },
  { heading: "<i class='fas fa-heart icon62'></i> Reward Your Effort", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task for <strong class='highlight2'>exclusive bonuses</strong> and grow your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-rocket icon63'></i> Boost Your Daily Rewards", text: "Complete your task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>premium bonuses</strong> and maintain your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-gem icon64'></i> Shine with Your Task", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your daily task to claim <strong class='highlight2'>special rewards</strong> and boost your <strong class='highlight'>daily income</strong>!" },
  { heading: "<i class='fas fa-trophy icon65'></i> Victory Awaits You", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to earn <strong class='highlight2'>exclusive prizes</strong> and keep your <strong class='highlight'>streak alive</strong>!" },
  { heading: "<i class='fas fa-bolt icon66'></i> Strike Today’s Task", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your task for <strong class='highlight2'>premium rewards</strong> and grow your <strong class='highlight'>daily streak</strong>!" },
  { heading: "<i class='fas fa-lightbulb icon67'></i> Bright Rewards Await", text: "Complete your daily task, <strong class='highlight'>Umarae user</strong>, to unlock <strong class='highlight2'>exclusive bonuses</strong> and maximize your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-chart-line icon68'></i> Track Your Daily Growth", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task for <strong class='highlight2'>special rewards</strong> and maintain your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-star-half-alt icon69'></i> Halfway to Extra Rewards", text: "Complete your task, <strong class='highlight'>Umarae user</strong>, to claim <strong class='highlight2'>premium bonuses</strong> and boost your <strong class='highlight'>daily income</strong>!" },
  { heading: "<i class='fas fa-moon icon70'></i> Nightly Bonus Awaits", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your daily task to unlock <strong class='highlight2'>special rewards</strong> and grow your <strong class='highlight'>streak</strong>!" },

  { heading: "<i class='fas fa-dice icon71'></i> Roll for Daily Rewards", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to earn <strong class='highlight2'>exclusive prizes</strong> and maintain your <strong class='highlight'>earning streak</strong>!" },
  { heading: "<i class='fas fa-paper-plane icon72'></i> Send Your Effort, Get Rewards", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task for <strong class='highlight2'>premium bonuses</strong> and boost your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-crown icon73'></i> Be the Daily Champion", text: "Complete your task, <strong class='highlight'>Umarae user</strong>, to claim <strong class='highlight2'>exclusive rewards</strong> and maximize your <strong class='highlight'>daily streak</strong>!" },
  { heading: "<i class='fas fa-clipboard icon74'></i> Check Off Today’s Task", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your daily task to unlock <strong class='highlight2'>special bonuses</strong> and keep your <strong class='highlight'>streak alive</strong>!" },
  { heading: "<i class='fas fa-bell icon75'></i> Reminder: Task Pending", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to earn <strong class='highlight2'>premium rewards</strong> and grow your <strong class='highlight'>daily income</strong>!" },
  { heading: "<i class='fas fa-key icon76'></i> Unlock Exclusive Bonuses", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task to claim <strong class='highlight2'>special rewards</strong> and maintain your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-paperclip icon77'></i> Clip Your Rewards", text: "Complete your task, <strong class='highlight'>Umarae user</strong> to earn <strong class='highlight2'>exclusive bonuses</strong> and boost your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-fire icon78'></i> Ignite Your Daily Gains", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task to unlock <strong class='highlight2'>premium rewards</strong> and grow your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-sun icon79'></i> Shine with Daily Rewards", text: "Complete your task, <strong class='highlight'>Umarae user</strong> to claim <strong class='highlight2'>special bonuses</strong> and boost your <strong class='highlight'>daily earnings</strong>!" },
  { heading: "<i class='fas fa-bullseye icon80'></i> Hit Your Daily Target", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task to earn <strong class='highlight2'>exclusive rewards</strong> and maintain your <strong class='highlight'>streak</strong>!" },

  { heading: "<i class='fas fa-gem icon81'></i> Collect Gems Daily", text: "Hello <strong class='highlight'>Umarae user</strong>! Complete today’s task to earn <strong class='highlight2'>bonus gems</strong> and grow your <strong class='highlight'>daily streak</strong>!" },
  { heading: "<i class='fas fa-rocket icon82'></i> Rocket Your Rewards", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish your task to unlock <strong class='highlight2'>premium bonuses</strong> and maximize your <strong class='highlight'>daily income</strong>!" },
  { heading: "<i class='fas fa-coins icon83'></i> Coins Await Today", text: "Complete your daily task, <strong class='highlight'>Umarae user</strong>, to earn <strong class='highlight2'>special coins</strong> and maintain your <strong class='highlight'>streak</strong>!" },
  { heading: "<i class='fas fa-star icon84'></i> Star in Your Daily Gains", text: "Hey <strong class='highlight'>Umarae member</strong>! Finish today’s task to unlock <strong class='highlight2'>exclusive bonuses</strong> and boost your <strong class='highlight'>daily rewards</strong>!" },
];

    const randomIndex = Math.floor(Math.random() * messages.length);
    const message = messages[randomIndex];

    document.getElementById('miningHeading').innerHTML = message.heading;
    document.getElementById('miningText').innerHTML = message.text;

    popup.style.display = 'flex';
  } else {
    popup.style.display = 'none';
  }

  closeBtn.addEventListener('click', () => {
    popup.style.display = 'none';
    // ✅ Save timestamp per page
    localStorage.setItem(pageKey, Date.now().toString());
  });
});
